services:
  react-app:
    build:
      context: .
      target: development
    ports:
      - "5173:5173"
    volumes:
      - .:/todo-client
      - todo-node-modules:/todo-client/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  todo-node-modules:
